---
# ====== Application: PTW_PRO ================================
identification: 
  name: PTW_PRO
  alias: PTW-PRO
  version: Release 1.0 [&APP_ENV.]

row-search: 
  tokenize: true
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Native Printing

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: false
  compatibility-mode: 24.2
  accessible-read-only-items: true
  pass-ecid: Y

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Oracle APEX Accounts # 26414203820144584

authorization: 
  authorization-scheme: Reader Rights # 30177956100539874
  run-on-public-pages: false
  run-on-background-job: true
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled
  maximum-session-idle-time: 3400
  session-timeout-warning: 3200

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Enabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended
  runtime-api-usage: 
  - Modify Workspace Repository

database-session: 
  parsing-schema: PTW_PRO

globalization: 
  primary-language: English (en)
  document-direction: Language Default
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text

progressive-web-app: 
  enable: true
  installable: true
  display: Fullscreen
  screen-orientation: Any
  ios-status-bar-style: Default
  enable-push-notifications: true
  pwa-push-notifications-credentials: App 105 Push Notifications Credentials # 30175822546549151

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&APP_SESSION.::&DEBUG.:::'
    page: 1 # Dashboard

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Side Navigation Menu
  template-options: 
  - '#DEFAULT#'
  - js-defaultCollapsed
  - js-navCollapsed--hidden
  - t-TreeNav--styleA
  list-position: Side
  list: Navigation Menu # 26415021693144587

navigation-bar: 
  implementation: List
  list: Navigation Bar # 26416210318144596
  list-template: Navigation Bar
  template-options: 
  - '#DEFAULT#'

javascript: 
  file-urls: 
  - '#APP_FILES#ptw-utils#MIN#.js'
  include-jquery-migrate: false

css: 
  file-urls: 
  - '#APP_FILES#ptw-global#MIN#.css'

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: false
  auto-dismiss-success-messages: false

subscription: 
  version-number: 49960837582845

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: PTW_PRO

- # ====== Substitution: APP_ENV ===============================
  id: 2
  identification: 
    name: APP_ENV

  value: 
    static-value: DEV

component-settings: 
- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 26409758641144568
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 46251647958994

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 26410080447144569
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 46251647959048

- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 26410349985144570
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  subscription: 
    version-number: 46251647959084

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 26410645930144571
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  subscription: 
    version-number: 46251647959084

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 26410999959144573
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 46251647959084

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 26411226682144574
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 46251647959086

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 26411520083144575
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  subscription: 
    version-number: 46251647959086

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 26411807586144576
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  subscription: 
    version-number: 46251647959086

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 26412113620144577
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  subscription: 
    version-number: 46251647959089

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 26412450836144578
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  subscription: 
    version-number: 46251647959099

- # ====== Component Setting: NATIVE_IR ========================
  id: 26412763991144579
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 46251647959100

- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 26413083481144580
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 46251647959101

- # ====== Component Setting: NATIVE_BOSS ======================
  id: 26413348463144581
  identification: 
    name: NATIVE_BOSS
    type: REST Data Source

  subscription: 
    version-number: 46251647959101

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 26413601387144582
  identification: 
    name: NATIVE_YES_NO
    type: Item

  subscription: 
    version-number: 46251647959101

application-settings: 
- # ====== Application Setting: ACCESS_CONTROL_SCOPE ===========
  id: 30176801618539885
  identification: 
    name: ACCESS_CONTROL_SCOPE

  value: 
    value: ACL_ONLY
    required: false

  advanced: 
    valid-values: ACL_ONLY, ALL_USERS
    on-upgrade-keep-value: true

  subscription: 
    version-number: 46397943188400

  configuration: 
    build-option: 'Feature: Access Control' # 30176569585539888

  comments: 
    comments: The default access level given to authenticated users who are not in the access control list

