prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@workspace/credentials/app_105_push_notifications_credentials.sql
@@application/shared_components/navigation/lists/navigation_menu.sql
@@application/shared_components/navigation/lists/navigation_bar.sql
@@application/shared_components/navigation/lists/user_settings.sql
@@application/shared_components/navigation/lists/access_control.sql
@@application/shared_components/navigation/lists/activity_reports.sql
@@application/shared_components/navigation/listentry.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_144_rounded_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_256_rounded_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/shared_components/files/bgis_logo_png.sql
@@application/shared_components/files/bgis_logo_jpg.sql
@@application/shared_components/files/geolocation_js.sql
@@application/shared_components/files/geolocation_min_js.sql
@@application/shared_components/files/offline_storage_js.sql
@@application/shared_components/files/offline_storage_min_js.sql
@@application/shared_components/files/ptw_utils_js.sql
@@application/shared_components/files/ptw_global_css.sql
@@application/shared_components/files/offline_nav_min_js.sql
@@application/shared_components/files/ptw_global_min_css.sql
@@application/shared_components/files/ptw_utils_min_js.sql
@@application/shared_components/files/offline_nav_js.sql
@@application/shared_components/files/offline_nav_min_js_002.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/security/authorizations/contribution_rights.sql
@@application/shared_components/security/authorizations/reader_rights.sql
@@application/shared_components/security/authorizations/is_administrator.sql
@@application/shared_components/security/authorizations/can_edit_permits.sql
@@application/shared_components/security/authorizations/can_authorise_permits.sql
@@application/shared_components/security/authorizations/can_delete_permits.sql
@@application/shared_components/security/authorizations/can_export_reports.sql
@@application/shared_components/security/authorizations/can_generate_pdf.sql
@@application/shared_components/security/app_access_control/administrator.sql
@@application/shared_components/security/app_access_control/contributor.sql
@@application/shared_components/security/app_access_control/reader.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/get_photo.sql
@@application/shared_components/logic/application_processes/get_signatures_p5.sql
@@application/shared_components/logic/application_processes/set_location.sql
@@application/shared_components/logic/application_items/app_is_admin.sql
@@application/shared_components/logic/application_items/app_is_engineer.sql
@@application/shared_components/logic/application_items/app_latitude.sql
@@application/shared_components/logic/application_items/app_longitude.sql
@@application/shared_components/logic/application_computations/app_is_engineer.sql
@@application/shared_components/logic/application_computations/app_is_admin.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/access_roles.sql
@@application/shared_components/user_interface/lovs/control_measures_lov.sql
@@application/shared_components/user_interface/lovs/email_username_format.sql
@@application/shared_components/user_interface/lovs/ptw_authorised_persons.sql
@@application/shared_components/user_interface/lovs/ptw_start_mode.sql
@@application/shared_components/user_interface/lovs/timeframe_4_weeks.sql
@@application/shared_components/user_interface/lovs/view_as_report_chart.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/report/ptw_cards_no_wrapper.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/automations/change_workflow_status.sql
@@application/shared_components/security/authentications/oracle_apex_accounts.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00007.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00010.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_00016.sql
@@application/pages/page_00017.sql
@@application/pages/page_00020.sql
@@application/pages/page_00050.sql
@@application/pages/page_00300.sql
@@application/pages/page_09999.sql
@@application/deployment/definition.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
