 CREATE OR REPLACE EDITIONABLE TRIGGER "PTW_PRO"."TRG_PTW_LV_TEAM_TYPES_AUDIT"
 BEFORE INSERT OR UPDATE ON ptw_pro.ptw_lv_team_types
 FOR EACH ROW
 BEGIN
     IF INSERTING THEN
         :NEW.created_date := SYSTIMESTAMP;
         :NEW.created_by   := NVL(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), USER);
     END IF;
     :NEW.modified_date := SYSTIMESTAMP;
     :NEW.modified_by   := NVL(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), USER);
 END;
 /
 ALTER TRIGGER "PTW_PRO"."TRG_PTW_LV_TEAM_TYPES_AUDIT" ENABLE;
 