
  CREATE OR REPLACE EDITIONABLE TRIGGER "PTW_PRO"."TRG_PTW_TYPES_AUDIT"
BEFORE INSERT ON ptw_pro.ptw_types
FOR EACH ROW
BEGIN
    :NEW.created_date := SYSDATE;
    :NEW.created_by   := NVL(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), USER);
END;

/
ALTER TRIGGER "PTW_PRO"."TRG_PTW_TYPES_AUDIT" ENABLE;
