
  CREATE OR REPLACE EDITIONABLE TRIGGER "PTW_PRO"."TRG_PTW_LV_COMPANY_TYPES_AUDIT"
BEFORE INSERT ON ptw_pro.ptw_lv_company_types
FOR EACH ROW
BEGIN
    :NEW.created_date  := SYSTIMESTAMP;
    :NEW.created_by    := NVL(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), USER);
    :NEW.modified_date := SYSTIMESTAMP;
    :NEW.modified_by   := NVL(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), USER);
END;

/
ALTER TRIGGER "PTW_PRO"."TRG_PTW_LV_COMPANY_TYPES_AUDIT" ENABLE;
