
  BEGIN DBMS_RLS.ADD_GROUPED_POLICY('"PTW_PRO"','"PTW_LV_COMPANY_TYPES"','"SYS_DEFAULT"','"PTW_COMPANY_POLICY"','"PTW_PRO"','"PTW_SEC_PKG"."COMPANY_POLICY"','DELETE,UPDATE,INSERT,SELECT',TRUE,TRUE,FALSE,dbms_rls.DYNAMIC,FALSE,'',NULL); END;
/

