SET LONG 1000000
SET LONGCHUNKSIZE 1000000
SET PAGESIZE 0
SET LINESIZE 32767
SET FEEDBACK OFF
SET ECHO OFF
SET VERIFY OFF
SET TRIMSPOOL ON
SET TERMOUT OFF

PROMPT Exporting table DEBUG_MESSAGES
SPOOL tables/debug_messages.sql
SELECT DBMS_METADATA.GET_DDL('TABLE', 'DEBUG_MESSAGES', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting table PTW_CHECKLIST_ITEMS
SPOOL tables/ptw_checklist_items.sql
SELECT DBMS_METADATA.GET_DDL('TABLE', 'PTW_CHECKLIST_ITEMS', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting table PTW_CHECKLIST_RESPONSES
SPOOL tables/ptw_checklist_responses.sql
SELECT DBMS_METADATA.GET_DDL('TABLE', 'PTW_CHECKLIST_RESPONSES', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting table PTW_LV_COMPANIES
SPOOL tables/ptw_lv_companies.sql
SELECT DBMS_METADATA.GET_DDL('TABLE', 'PTW_LV_COMPANIES', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting table PTW_LV_COMPANY_TYPES
SPOOL tables/ptw_lv_company_types.sql
SELECT DBMS_METADATA.GET_DDL('TABLE', 'PTW_LV_COMPANY_TYPES', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting table PTW_LV_CONTROL_MEASURES
SPOOL tables/ptw_lv_control_measures.sql
SELECT DBMS_METADATA.GET_DDL('TABLE', 'PTW_LV_CONTROL_MEASURES', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting table PTW_LV_EQUIPMENT_ISOLATION
SPOOL tables/ptw_lv_equipment_isolation.sql
SELECT DBMS_METADATA.GET_DDL('TABLE', 'PTW_LV_EQUIPMENT_ISOLATION', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting table PTW_LV_MONITORING
SPOOL tables/ptw_lv_monitoring.sql
SELECT DBMS_METADATA.GET_DDL('TABLE', 'PTW_LV_MONITORING', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting table PTW_LV_MONITORING_CONCERNS
SPOOL tables/ptw_lv_monitoring_concerns.sql
SELECT DBMS_METADATA.GET_DDL('TABLE', 'PTW_LV_MONITORING_CONCERNS', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting table PTW_LV_PERMITS
SPOOL tables/ptw_lv_permits.sql
SELECT DBMS_METADATA.GET_DDL('TABLE', 'PTW_LV_PERMITS', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting table PTW_LV_PERMIT_PHOTOS
SPOOL tables/ptw_lv_permit_photos.sql
SELECT DBMS_METADATA.GET_DDL('TABLE', 'PTW_LV_PERMIT_PHOTOS', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting table PTW_LV_ROLES
SPOOL tables/ptw_lv_roles.sql
SELECT DBMS_METADATA.GET_DDL('TABLE', 'PTW_LV_ROLES', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting table PTW_LV_SITES
SPOOL tables/ptw_lv_sites.sql
SELECT DBMS_METADATA.GET_DDL('TABLE', 'PTW_LV_SITES', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting table PTW_LV_TEAMS
SPOOL tables/ptw_lv_teams.sql
SELECT DBMS_METADATA.GET_DDL('TABLE', 'PTW_LV_TEAMS', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting table PTW_LV_TEAM_TYPES
SPOOL tables/ptw_lv_team_types.sql
SELECT DBMS_METADATA.GET_DDL('TABLE', 'PTW_LV_TEAM_TYPES', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting table PTW_LV_USERS
SPOOL tables/ptw_lv_users.sql
SELECT DBMS_METADATA.GET_DDL('TABLE', 'PTW_LV_USERS', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting table PTW_LV_USER_ROLES_OLD
SPOOL tables/ptw_lv_user_roles_old.sql
SELECT DBMS_METADATA.GET_DDL('TABLE', 'PTW_LV_USER_ROLES_OLD', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting table PTW_LV_USER_ROLE_ASSIGNMENTS
SPOOL tables/ptw_lv_user_role_assignments.sql
SELECT DBMS_METADATA.GET_DDL('TABLE', 'PTW_LV_USER_ROLE_ASSIGNMENTS', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting table PTW_LV_USER_TYPES
SPOOL tables/ptw_lv_user_types.sql
SELECT DBMS_METADATA.GET_DDL('TABLE', 'PTW_LV_USER_TYPES', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting table PTW_MONITORING_CHECKS
SPOOL tables/ptw_monitoring_checks.sql
SELECT DBMS_METADATA.GET_DDL('TABLE', 'PTW_MONITORING_CHECKS', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting table PTW_SIGNATURES
SPOOL tables/ptw_signatures.sql
SELECT DBMS_METADATA.GET_DDL('TABLE', 'PTW_SIGNATURES', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting table PTW_STAGE_LOCATIONS
SPOOL tables/ptw_stage_locations.sql
SELECT DBMS_METADATA.GET_DDL('TABLE', 'PTW_STAGE_LOCATIONS', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting table PTW_TYPES
SPOOL tables/ptw_types.sql
SELECT DBMS_METADATA.GET_DDL('TABLE', 'PTW_TYPES', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting table PTW_TYPE_SECTIONS
SPOOL tables/ptw_type_sections.sql
SELECT DBMS_METADATA.GET_DDL('TABLE', 'PTW_TYPE_SECTIONS', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting constraints for DEBUG_MESSAGES
SPOOL tables/debug_messages.sql APPEND
BEGIN
    DBMS_OUTPUT.PUT_LINE(NVL(DBMS_METADATA.GET_DEPENDENT_DDL('CONSTRAINT', 'DEBUG_MESSAGES', 'PTW_PRO'), ''));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
PROMPT Exporting constraints for PTW_CHECKLIST_ITEMS
SPOOL tables/ptw_checklist_items.sql APPEND
BEGIN
    DBMS_OUTPUT.PUT_LINE(NVL(DBMS_METADATA.GET_DEPENDENT_DDL('CONSTRAINT', 'PTW_CHECKLIST_ITEMS', 'PTW_PRO'), ''));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
PROMPT Exporting constraints for PTW_CHECKLIST_RESPONSES
SPOOL tables/ptw_checklist_responses.sql APPEND
BEGIN
    DBMS_OUTPUT.PUT_LINE(NVL(DBMS_METADATA.GET_DEPENDENT_DDL('CONSTRAINT', 'PTW_CHECKLIST_RESPONSES', 'PTW_PRO'), ''));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
PROMPT Exporting constraints for PTW_LV_COMPANIES
SPOOL tables/ptw_lv_companies.sql APPEND
BEGIN
    DBMS_OUTPUT.PUT_LINE(NVL(DBMS_METADATA.GET_DEPENDENT_DDL('CONSTRAINT', 'PTW_LV_COMPANIES', 'PTW_PRO'), ''));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
PROMPT Exporting constraints for PTW_LV_COMPANY_TYPES
SPOOL tables/ptw_lv_company_types.sql APPEND
BEGIN
    DBMS_OUTPUT.PUT_LINE(NVL(DBMS_METADATA.GET_DEPENDENT_DDL('CONSTRAINT', 'PTW_LV_COMPANY_TYPES', 'PTW_PRO'), ''));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
PROMPT Exporting constraints for PTW_LV_CONTROL_MEASURES
SPOOL tables/ptw_lv_control_measures.sql APPEND
BEGIN
    DBMS_OUTPUT.PUT_LINE(NVL(DBMS_METADATA.GET_DEPENDENT_DDL('CONSTRAINT', 'PTW_LV_CONTROL_MEASURES', 'PTW_PRO'), ''));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
PROMPT Exporting constraints for PTW_LV_EQUIPMENT_ISOLATION
SPOOL tables/ptw_lv_equipment_isolation.sql APPEND
BEGIN
    DBMS_OUTPUT.PUT_LINE(NVL(DBMS_METADATA.GET_DEPENDENT_DDL('CONSTRAINT', 'PTW_LV_EQUIPMENT_ISOLATION', 'PTW_PRO'), ''));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
PROMPT Exporting constraints for PTW_LV_MONITORING
SPOOL tables/ptw_lv_monitoring.sql APPEND
BEGIN
    DBMS_OUTPUT.PUT_LINE(NVL(DBMS_METADATA.GET_DEPENDENT_DDL('CONSTRAINT', 'PTW_LV_MONITORING', 'PTW_PRO'), ''));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
PROMPT Exporting constraints for PTW_LV_MONITORING_CONCERNS
SPOOL tables/ptw_lv_monitoring_concerns.sql APPEND
BEGIN
    DBMS_OUTPUT.PUT_LINE(NVL(DBMS_METADATA.GET_DEPENDENT_DDL('CONSTRAINT', 'PTW_LV_MONITORING_CONCERNS', 'PTW_PRO'), ''));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
PROMPT Exporting constraints for PTW_LV_PERMITS
SPOOL tables/ptw_lv_permits.sql APPEND
BEGIN
    DBMS_OUTPUT.PUT_LINE(NVL(DBMS_METADATA.GET_DEPENDENT_DDL('CONSTRAINT', 'PTW_LV_PERMITS', 'PTW_PRO'), ''));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
PROMPT Exporting constraints for PTW_LV_PERMIT_PHOTOS
SPOOL tables/ptw_lv_permit_photos.sql APPEND
BEGIN
    DBMS_OUTPUT.PUT_LINE(NVL(DBMS_METADATA.GET_DEPENDENT_DDL('CONSTRAINT', 'PTW_LV_PERMIT_PHOTOS', 'PTW_PRO'), ''));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
PROMPT Exporting constraints for PTW_LV_ROLES
SPOOL tables/ptw_lv_roles.sql APPEND
BEGIN
    DBMS_OUTPUT.PUT_LINE(NVL(DBMS_METADATA.GET_DEPENDENT_DDL('CONSTRAINT', 'PTW_LV_ROLES', 'PTW_PRO'), ''));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
PROMPT Exporting constraints for PTW_LV_SITES
SPOOL tables/ptw_lv_sites.sql APPEND
BEGIN
    DBMS_OUTPUT.PUT_LINE(NVL(DBMS_METADATA.GET_DEPENDENT_DDL('CONSTRAINT', 'PTW_LV_SITES', 'PTW_PRO'), ''));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
PROMPT Exporting constraints for PTW_LV_TEAMS
SPOOL tables/ptw_lv_teams.sql APPEND
BEGIN
    DBMS_OUTPUT.PUT_LINE(NVL(DBMS_METADATA.GET_DEPENDENT_DDL('CONSTRAINT', 'PTW_LV_TEAMS', 'PTW_PRO'), ''));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
PROMPT Exporting constraints for PTW_LV_TEAM_TYPES
SPOOL tables/ptw_lv_team_types.sql APPEND
BEGIN
    DBMS_OUTPUT.PUT_LINE(NVL(DBMS_METADATA.GET_DEPENDENT_DDL('CONSTRAINT', 'PTW_LV_TEAM_TYPES', 'PTW_PRO'), ''));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
PROMPT Exporting constraints for PTW_LV_USERS
SPOOL tables/ptw_lv_users.sql APPEND
BEGIN
    DBMS_OUTPUT.PUT_LINE(NVL(DBMS_METADATA.GET_DEPENDENT_DDL('CONSTRAINT', 'PTW_LV_USERS', 'PTW_PRO'), ''));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
PROMPT Exporting constraints for PTW_LV_USER_ROLES_OLD
SPOOL tables/ptw_lv_user_roles_old.sql APPEND
BEGIN
    DBMS_OUTPUT.PUT_LINE(NVL(DBMS_METADATA.GET_DEPENDENT_DDL('CONSTRAINT', 'PTW_LV_USER_ROLES_OLD', 'PTW_PRO'), ''));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
PROMPT Exporting constraints for PTW_LV_USER_ROLE_ASSIGNMENTS
SPOOL tables/ptw_lv_user_role_assignments.sql APPEND
BEGIN
    DBMS_OUTPUT.PUT_LINE(NVL(DBMS_METADATA.GET_DEPENDENT_DDL('CONSTRAINT', 'PTW_LV_USER_ROLE_ASSIGNMENTS', 'PTW_PRO'), ''));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
PROMPT Exporting constraints for PTW_LV_USER_TYPES
SPOOL tables/ptw_lv_user_types.sql APPEND
BEGIN
    DBMS_OUTPUT.PUT_LINE(NVL(DBMS_METADATA.GET_DEPENDENT_DDL('CONSTRAINT', 'PTW_LV_USER_TYPES', 'PTW_PRO'), ''));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
PROMPT Exporting constraints for PTW_MONITORING_CHECKS
SPOOL tables/ptw_monitoring_checks.sql APPEND
BEGIN
    DBMS_OUTPUT.PUT_LINE(NVL(DBMS_METADATA.GET_DEPENDENT_DDL('CONSTRAINT', 'PTW_MONITORING_CHECKS', 'PTW_PRO'), ''));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
PROMPT Exporting constraints for PTW_SIGNATURES
SPOOL tables/ptw_signatures.sql APPEND
BEGIN
    DBMS_OUTPUT.PUT_LINE(NVL(DBMS_METADATA.GET_DEPENDENT_DDL('CONSTRAINT', 'PTW_SIGNATURES', 'PTW_PRO'), ''));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
PROMPT Exporting constraints for PTW_STAGE_LOCATIONS
SPOOL tables/ptw_stage_locations.sql APPEND
BEGIN
    DBMS_OUTPUT.PUT_LINE(NVL(DBMS_METADATA.GET_DEPENDENT_DDL('CONSTRAINT', 'PTW_STAGE_LOCATIONS', 'PTW_PRO'), ''));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
PROMPT Exporting constraints for PTW_TYPES
SPOOL tables/ptw_types.sql APPEND
BEGIN
    DBMS_OUTPUT.PUT_LINE(NVL(DBMS_METADATA.GET_DEPENDENT_DDL('CONSTRAINT', 'PTW_TYPES', 'PTW_PRO'), ''));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
PROMPT Exporting constraints for PTW_TYPE_SECTIONS
SPOOL tables/ptw_type_sections.sql APPEND
BEGIN
    DBMS_OUTPUT.PUT_LINE(NVL(DBMS_METADATA.GET_DEPENDENT_DDL('CONSTRAINT', 'PTW_TYPE_SECTIONS', 'PTW_PRO'), ''));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
SET SERVEROUTPUT ON
PROMPT Exporting index IDX_PTW_CI_TYPE
SPOOL indexes/idx_ptw_ci_type.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'IDX_PTW_CI_TYPE', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting index IDX_PTW_CR_ITEM
SPOOL indexes/idx_ptw_cr_item.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'IDX_PTW_CR_ITEM', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting index IDX_PTW_CR_PERMIT
SPOOL indexes/idx_ptw_cr_permit.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'IDX_PTW_CR_PERMIT', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting index IDX_PTW_LV_CM_COMPANY
SPOOL indexes/idx_ptw_lv_cm_company.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'IDX_PTW_LV_CM_COMPANY', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting index IDX_PTW_LV_CM_PERMIT
SPOOL indexes/idx_ptw_lv_cm_permit.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'IDX_PTW_LV_CM_PERMIT', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting index IDX_PTW_LV_CO_TYPES_COMPANY
SPOOL indexes/idx_ptw_lv_co_types_company.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'IDX_PTW_LV_CO_TYPES_COMPANY', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting index IDX_PTW_LV_CO_TYPES_TYPE
SPOOL indexes/idx_ptw_lv_co_types_type.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'IDX_PTW_LV_CO_TYPES_TYPE', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting index IDX_PTW_LV_ISO_COMPANY
SPOOL indexes/idx_ptw_lv_iso_company.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'IDX_PTW_LV_ISO_COMPANY', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting index IDX_PTW_LV_ISO_PERMIT
SPOOL indexes/idx_ptw_lv_iso_permit.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'IDX_PTW_LV_ISO_PERMIT', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting index IDX_PTW_LV_MON_COMPANY
SPOOL indexes/idx_ptw_lv_mon_company.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'IDX_PTW_LV_MON_COMPANY', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting index IDX_PTW_LV_MON_PERMIT
SPOOL indexes/idx_ptw_lv_mon_permit.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'IDX_PTW_LV_MON_PERMIT', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting index IDX_PTW_LV_PERMITS_COMPANY
SPOOL indexes/idx_ptw_lv_permits_company.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'IDX_PTW_LV_PERMITS_COMPANY', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting index IDX_PTW_LV_PERMITS_SITE
SPOOL indexes/idx_ptw_lv_permits_site.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'IDX_PTW_LV_PERMITS_SITE', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting index IDX_PTW_LV_PERM_CREATED
SPOOL indexes/idx_ptw_lv_perm_created.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'IDX_PTW_LV_PERM_CREATED', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting index IDX_PTW_LV_PERM_STATUS
SPOOL indexes/idx_ptw_lv_perm_status.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'IDX_PTW_LV_PERM_STATUS', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting index IDX_PTW_LV_PHOTOS_CONCERN
SPOOL indexes/idx_ptw_lv_photos_concern.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'IDX_PTW_LV_PHOTOS_CONCERN', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting index IDX_PTW_LV_PHOTOS_PERMIT
SPOOL indexes/idx_ptw_lv_photos_permit.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'IDX_PTW_LV_PHOTOS_PERMIT', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting index IDX_PTW_LV_PHO_COMPANY
SPOOL indexes/idx_ptw_lv_pho_company.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'IDX_PTW_LV_PHO_COMPANY', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting index IDX_PTW_LV_SITES_COMPANY
SPOOL indexes/idx_ptw_lv_sites_company.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'IDX_PTW_LV_SITES_COMPANY', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting index IDX_PTW_LV_TEAMS_COMPANY
SPOOL indexes/idx_ptw_lv_teams_company.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'IDX_PTW_LV_TEAMS_COMPANY', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting index IDX_PTW_LV_TEAM_TYPES_COMPANY
SPOOL indexes/idx_ptw_lv_team_types_company.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'IDX_PTW_LV_TEAM_TYPES_COMPANY', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting index IDX_PTW_LV_TEAM_TYPES_TEAM
SPOOL indexes/idx_ptw_lv_team_types_team.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'IDX_PTW_LV_TEAM_TYPES_TEAM', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting index IDX_PTW_LV_UR_USERNAME
SPOOL indexes/idx_ptw_lv_ur_username.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'IDX_PTW_LV_UR_USERNAME', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting index IDX_PTW_LV_USERS_COMPANY
SPOOL indexes/idx_ptw_lv_users_company.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'IDX_PTW_LV_USERS_COMPANY', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting index IDX_PTW_LV_USERS_TEAM
SPOOL indexes/idx_ptw_lv_users_team.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'IDX_PTW_LV_USERS_TEAM', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting index IDX_PTW_LV_USER_TYPES_COMPANY
SPOOL indexes/idx_ptw_lv_user_types_company.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'IDX_PTW_LV_USER_TYPES_COMPANY', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting index IDX_PTW_LV_USER_TYPES_USER
SPOOL indexes/idx_ptw_lv_user_types_user.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'IDX_PTW_LV_USER_TYPES_USER', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting index IDX_PTW_MC_MONITORING
SPOOL indexes/idx_ptw_mc_monitoring.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'IDX_PTW_MC_MONITORING', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting index IDX_PTW_SIG_PERMIT
SPOOL indexes/idx_ptw_sig_permit.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'IDX_PTW_SIG_PERMIT', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting index IDX_PTW_STAGE_LOC_COMPANY
SPOOL indexes/idx_ptw_stage_loc_company.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'IDX_PTW_STAGE_LOC_COMPANY', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting index IDX_PTW_STAGE_LOC_PERMIT
SPOOL indexes/idx_ptw_stage_loc_permit.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'IDX_PTW_STAGE_LOC_PERMIT', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting index SYS_IL0000149023C00026$$
SPOOL indexes/sys_il0000149023c00026$$.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'SYS_IL0000149023C00026$$', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting index SYS_IL0000149023C00032$$
SPOOL indexes/sys_il0000149023c00032$$.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'SYS_IL0000149023C00032$$', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting index SYS_IL0000149023C00041$$
SPOOL indexes/sys_il0000149023c00041$$.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'SYS_IL0000149023C00041$$', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting index SYS_IL0000149023C00049$$
SPOOL indexes/sys_il0000149023c00049$$.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'SYS_IL0000149023C00049$$', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting index SYS_IL0000164554C00003$$
SPOOL indexes/sys_il0000164554c00003$$.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'SYS_IL0000164554C00003$$', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting index SYS_IL0000166174C00022$$
SPOOL indexes/sys_il0000166174c00022$$.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'SYS_IL0000166174C00022$$', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting index SYS_IL0000199987C00008$$
SPOOL indexes/sys_il0000199987c00008$$.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'SYS_IL0000199987C00008$$', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting index SYS_IL0000207358C00005$$
SPOOL indexes/sys_il0000207358c00005$$.sql
SELECT DBMS_METADATA.GET_DDL('INDEX', 'SYS_IL0000207358C00005$$', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting sequence PTW_CHECKLIST_ITEM_SEQ
SPOOL sequences/ptw_checklist_item_seq.sql
SELECT DBMS_METADATA.GET_DDL('SEQUENCE', 'PTW_CHECKLIST_ITEM_SEQ', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting sequence PTW_CHECKLIST_RESPONSE_SEQ
SPOOL sequences/ptw_checklist_response_seq.sql
SELECT DBMS_METADATA.GET_DDL('SEQUENCE', 'PTW_CHECKLIST_RESPONSE_SEQ', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting sequence PTW_LV_CONTROL_MEASURES_SEQ
SPOOL sequences/ptw_lv_control_measures_seq.sql
SELECT DBMS_METADATA.GET_DDL('SEQUENCE', 'PTW_LV_CONTROL_MEASURES_SEQ', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting sequence PTW_LV_EQUIPMENT_ISOLATION_SEQ
SPOOL sequences/ptw_lv_equipment_isolation_seq.sql
SELECT DBMS_METADATA.GET_DDL('SEQUENCE', 'PTW_LV_EQUIPMENT_ISOLATION_SEQ', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting sequence PTW_LV_MONITORING_CONCERN_SEQ
SPOOL sequences/ptw_lv_monitoring_concern_seq.sql
SELECT DBMS_METADATA.GET_DDL('SEQUENCE', 'PTW_LV_MONITORING_CONCERN_SEQ', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting sequence PTW_LV_MONITORING_SEQ
SPOOL sequences/ptw_lv_monitoring_seq.sql
SELECT DBMS_METADATA.GET_DDL('SEQUENCE', 'PTW_LV_MONITORING_SEQ', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting sequence PTW_LV_PERMIT_SEQ
SPOOL sequences/ptw_lv_permit_seq.sql
SELECT DBMS_METADATA.GET_DDL('SEQUENCE', 'PTW_LV_PERMIT_SEQ', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting sequence PTW_LV_PHOTO_SEQ
SPOOL sequences/ptw_lv_photo_seq.sql
SELECT DBMS_METADATA.GET_DDL('SEQUENCE', 'PTW_LV_PHOTO_SEQ', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting sequence PTW_MONITORING_CHECK_SEQ
SPOOL sequences/ptw_monitoring_check_seq.sql
SELECT DBMS_METADATA.GET_DDL('SEQUENCE', 'PTW_MONITORING_CHECK_SEQ', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting sequence PTW_SIGNATURE_SEQ
SPOOL sequences/ptw_signature_seq.sql
SELECT DBMS_METADATA.GET_DDL('SEQUENCE', 'PTW_SIGNATURE_SEQ', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting sequence PTW_TYPE_ID_SEQ
SPOOL sequences/ptw_type_id_seq.sql
SELECT DBMS_METADATA.GET_DDL('SEQUENCE', 'PTW_TYPE_ID_SEQ', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting view PTW_LV_ANALYTICS_V
SPOOL views/ptw_lv_analytics_v.sql
SELECT DBMS_METADATA.GET_DDL('VIEW', 'PTW_LV_ANALYTICS_V', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting view PTW_LV_CANCELLATION_REASON_V
SPOOL views/ptw_lv_cancellation_reason_v.sql
SELECT DBMS_METADATA.GET_DDL('VIEW', 'PTW_LV_CANCELLATION_REASON_V', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting view PTW_LV_EFFECTIVE_TYPES_V
SPOOL views/ptw_lv_effective_types_v.sql
SELECT DBMS_METADATA.GET_DDL('VIEW', 'PTW_LV_EFFECTIVE_TYPES_V', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting view PTW_LV_USER_ROLES_V
SPOOL views/ptw_lv_user_roles_v.sql
SELECT DBMS_METADATA.GET_DDL('VIEW', 'PTW_LV_USER_ROLES_V', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting trigger PTW_LV_CONTROL_MEASURES_STAGE_LOC_TRG
SPOOL triggers/ptw_lv_control_measures_stage_loc_trg.sql
SELECT DBMS_METADATA.GET_DDL('TRIGGER', 'PTW_LV_CONTROL_MEASURES_STAGE_LOC_TRG', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting trigger PTW_LV_MONITORING_STAGE_LOC_TRG
SPOOL triggers/ptw_lv_monitoring_stage_loc_trg.sql
SELECT DBMS_METADATA.GET_DDL('TRIGGER', 'PTW_LV_MONITORING_STAGE_LOC_TRG', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting trigger PTW_LV_PERMITS_STAGE_LOC_TRG
SPOOL triggers/ptw_lv_permits_stage_loc_trg.sql
SELECT DBMS_METADATA.GET_DDL('TRIGGER', 'PTW_LV_PERMITS_STAGE_LOC_TRG', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting trigger TRG_PTW_CHECKLIST_ITEMS_AUDIT
SPOOL triggers/trg_ptw_checklist_items_audit.sql
SELECT DBMS_METADATA.GET_DDL('TRIGGER', 'TRG_PTW_CHECKLIST_ITEMS_AUDIT', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting trigger TRG_PTW_LV_CM_COMPANY
SPOOL triggers/trg_ptw_lv_cm_company.sql
SELECT DBMS_METADATA.GET_DDL('TRIGGER', 'TRG_PTW_LV_CM_COMPANY', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting trigger TRG_PTW_LV_COMPANIES_AUDIT
SPOOL triggers/trg_ptw_lv_companies_audit.sql
SELECT DBMS_METADATA.GET_DDL('TRIGGER', 'TRG_PTW_LV_COMPANIES_AUDIT', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting trigger TRG_PTW_LV_COMPANY_TYPES_AUDIT
SPOOL triggers/trg_ptw_lv_company_types_audit.sql
SELECT DBMS_METADATA.GET_DDL('TRIGGER', 'TRG_PTW_LV_COMPANY_TYPES_AUDIT', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting trigger TRG_PTW_LV_ISO_COMPANY
SPOOL triggers/trg_ptw_lv_iso_company.sql
SELECT DBMS_METADATA.GET_DDL('TRIGGER', 'TRG_PTW_LV_ISO_COMPANY', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting trigger TRG_PTW_LV_MC_COMPANY
SPOOL triggers/trg_ptw_lv_mc_company.sql
SELECT DBMS_METADATA.GET_DDL('TRIGGER', 'TRG_PTW_LV_MC_COMPANY', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting trigger TRG_PTW_LV_MON_COMPANY
SPOOL triggers/trg_ptw_lv_mon_company.sql
SELECT DBMS_METADATA.GET_DDL('TRIGGER', 'TRG_PTW_LV_MON_COMPANY', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting trigger TRG_PTW_LV_PERMITS_COMPANY
SPOOL triggers/trg_ptw_lv_permits_company.sql
SELECT DBMS_METADATA.GET_DDL('TRIGGER', 'TRG_PTW_LV_PERMITS_COMPANY', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting trigger TRG_PTW_LV_PERMIT_NUMBER
SPOOL triggers/trg_ptw_lv_permit_number.sql
SELECT DBMS_METADATA.GET_DDL('TRIGGER', 'TRG_PTW_LV_PERMIT_NUMBER', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting trigger TRG_PTW_LV_PHO_COMPANY
SPOOL triggers/trg_ptw_lv_pho_company.sql
SELECT DBMS_METADATA.GET_DDL('TRIGGER', 'TRG_PTW_LV_PHO_COMPANY', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting trigger TRG_PTW_LV_SITES_AUDIT
SPOOL triggers/trg_ptw_lv_sites_audit.sql
SELECT DBMS_METADATA.GET_DDL('TRIGGER', 'TRG_PTW_LV_SITES_AUDIT', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting trigger TRG_PTW_LV_TEAMS_AUDIT
SPOOL triggers/trg_ptw_lv_teams_audit.sql
SELECT DBMS_METADATA.GET_DDL('TRIGGER', 'TRG_PTW_LV_TEAMS_AUDIT', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting trigger TRG_PTW_LV_TEAM_TYPES_AUDIT
SPOOL triggers/trg_ptw_lv_team_types_audit.sql
SELECT DBMS_METADATA.GET_DDL('TRIGGER', 'TRG_PTW_LV_TEAM_TYPES_AUDIT', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting trigger TRG_PTW_LV_USER_TYPES_AUDIT
SPOOL triggers/trg_ptw_lv_user_types_audit.sql
SELECT DBMS_METADATA.GET_DDL('TRIGGER', 'TRG_PTW_LV_USER_TYPES_AUDIT', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting trigger TRG_PTW_TYPES_AUDIT
SPOOL triggers/trg_ptw_types_audit.sql
SELECT DBMS_METADATA.GET_DDL('TRIGGER', 'TRG_PTW_TYPES_AUDIT', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting function GENERATE_PTW_GENERAL_PDF
SPOOL functions/generate_ptw_general_pdf.sql
SELECT DBMS_METADATA.GET_DDL('FUNCTION', 'GENERATE_PTW_GENERAL_PDF', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting function GENERATE_PTW_LV_PDF
SPOOL functions/generate_ptw_lv_pdf.sql
SELECT DBMS_METADATA.GET_DDL('FUNCTION', 'GENERATE_PTW_LV_PDF', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting function GENERATE_PTW_PERMIT_PDF
SPOOL functions/generate_ptw_permit_pdf.sql
SELECT DBMS_METADATA.GET_DDL('FUNCTION', 'GENERATE_PTW_PERMIT_PDF', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting function GENERATE_PTW_WAH_PDF
SPOOL functions/generate_ptw_wah_pdf.sql
SELECT DBMS_METADATA.GET_DDL('FUNCTION', 'GENERATE_PTW_WAH_PDF', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting function PTW_LV_IS_CONTRACT_SUPPORT
SPOOL functions/ptw_lv_is_contract_support.sql
SELECT DBMS_METADATA.GET_DDL('FUNCTION', 'PTW_LV_IS_CONTRACT_SUPPORT', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting function PTW_LV_PERMIT_VISIBLE
SPOOL functions/ptw_lv_permit_visible.sql
SELECT DBMS_METADATA.GET_DDL('FUNCTION', 'PTW_LV_PERMIT_VISIBLE', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting package spec PTW_CHECKLIST_PKG
SPOOL packages/ptw_checklist_pkg.pks.sql
SELECT DBMS_METADATA.GET_DDL('PACKAGE', 'PTW_CHECKLIST_PKG', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting package spec PTW_MONITORING_PKG
SPOOL packages/ptw_monitoring_pkg.pks.sql
SELECT DBMS_METADATA.GET_DDL('PACKAGE', 'PTW_MONITORING_PKG', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting package spec PTW_PDF_LIB_PKG
SPOOL packages/ptw_pdf_lib_pkg.pks.sql
SELECT DBMS_METADATA.GET_DDL('PACKAGE', 'PTW_PDF_LIB_PKG', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting package spec PTW_PERMIT_SAVE_PKG
SPOOL packages/ptw_permit_save_pkg.pks.sql
SELECT DBMS_METADATA.GET_DDL('PACKAGE', 'PTW_PERMIT_SAVE_PKG', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting package spec PTW_SEC_PKG
SPOOL packages/ptw_sec_pkg.pks.sql
SELECT DBMS_METADATA.GET_DDL('PACKAGE', 'PTW_SEC_PKG', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting package spec PTW_SIGNATURE_PKG
SPOOL packages/ptw_signature_pkg.pks.sql
SELECT DBMS_METADATA.GET_DDL('PACKAGE', 'PTW_SIGNATURE_PKG', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting package spec PTW_UI_PKG
SPOOL packages/ptw_ui_pkg.pks.sql
SELECT DBMS_METADATA.GET_DDL('PACKAGE', 'PTW_UI_PKG', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting package body PTW_CHECKLIST_PKG
SPOOL packages/ptw_checklist_pkg.pkb.sql
SELECT DBMS_METADATA.GET_DDL('PACKAGE_BODY', 'PTW_CHECKLIST_PKG', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting package body PTW_MONITORING_PKG
SPOOL packages/ptw_monitoring_pkg.pkb.sql
SELECT DBMS_METADATA.GET_DDL('PACKAGE_BODY', 'PTW_MONITORING_PKG', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting package body PTW_PDF_LIB_PKG
SPOOL packages/ptw_pdf_lib_pkg.pkb.sql
SELECT DBMS_METADATA.GET_DDL('PACKAGE_BODY', 'PTW_PDF_LIB_PKG', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting package body PTW_PERMIT_SAVE_PKG
SPOOL packages/ptw_permit_save_pkg.pkb.sql
SELECT DBMS_METADATA.GET_DDL('PACKAGE_BODY', 'PTW_PERMIT_SAVE_PKG', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting package body PTW_SEC_PKG
SPOOL packages/ptw_sec_pkg.pkb.sql
SELECT DBMS_METADATA.GET_DDL('PACKAGE_BODY', 'PTW_SEC_PKG', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting package body PTW_SIGNATURE_PKG
SPOOL packages/ptw_signature_pkg.pkb.sql
SELECT DBMS_METADATA.GET_DDL('PACKAGE_BODY', 'PTW_SIGNATURE_PKG', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting package body PTW_UI_PKG
SPOOL packages/ptw_ui_pkg.pkb.sql
SELECT DBMS_METADATA.GET_DDL('PACKAGE_BODY', 'PTW_UI_PKG', 'PTW_PRO') FROM DUAL;
SPOOL OFF
PROMPT Exporting RLS policies for PTW_LV_PERMITS
SPOOL policies/ptw_lv_permits_policies.sql
SET SERVEROUTPUT ON
BEGIN
    DBMS_OUTPUT.PUT_LINE(DBMS_METADATA.GET_DEPENDENT_DDL('RLS_POLICY', 'PTW_LV_PERMITS', 'PTW_PRO'));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
PROMPT Exporting RLS policies for PTW_LV_CONTROL_MEASURES
SPOOL policies/ptw_lv_control_measures_policies.sql
SET SERVEROUTPUT ON
BEGIN
    DBMS_OUTPUT.PUT_LINE(DBMS_METADATA.GET_DEPENDENT_DDL('RLS_POLICY', 'PTW_LV_CONTROL_MEASURES', 'PTW_PRO'));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
PROMPT Exporting RLS policies for PTW_LV_EQUIPMENT_ISOLATION
SPOOL policies/ptw_lv_equipment_isolation_policies.sql
SET SERVEROUTPUT ON
BEGIN
    DBMS_OUTPUT.PUT_LINE(DBMS_METADATA.GET_DEPENDENT_DDL('RLS_POLICY', 'PTW_LV_EQUIPMENT_ISOLATION', 'PTW_PRO'));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
PROMPT Exporting RLS policies for PTW_STAGE_LOCATIONS
SPOOL policies/ptw_stage_locations_policies.sql
SET SERVEROUTPUT ON
BEGIN
    DBMS_OUTPUT.PUT_LINE(DBMS_METADATA.GET_DEPENDENT_DDL('RLS_POLICY', 'PTW_STAGE_LOCATIONS', 'PTW_PRO'));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
PROMPT Exporting RLS policies for PTW_LV_PERMIT_PHOTOS
SPOOL policies/ptw_lv_permit_photos_policies.sql
SET SERVEROUTPUT ON
BEGIN
    DBMS_OUTPUT.PUT_LINE(DBMS_METADATA.GET_DEPENDENT_DDL('RLS_POLICY', 'PTW_LV_PERMIT_PHOTOS', 'PTW_PRO'));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
PROMPT Exporting RLS policies for PTW_LV_MONITORING
SPOOL policies/ptw_lv_monitoring_policies.sql
SET SERVEROUTPUT ON
BEGIN
    DBMS_OUTPUT.PUT_LINE(DBMS_METADATA.GET_DEPENDENT_DDL('RLS_POLICY', 'PTW_LV_MONITORING', 'PTW_PRO'));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
PROMPT Exporting RLS policies for PTW_LV_COMPANY_TYPES
SPOOL policies/ptw_lv_company_types_policies.sql
SET SERVEROUTPUT ON
BEGIN
    DBMS_OUTPUT.PUT_LINE(DBMS_METADATA.GET_DEPENDENT_DDL('RLS_POLICY', 'PTW_LV_COMPANY_TYPES', 'PTW_PRO'));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
PROMPT Exporting RLS policies for PTW_LV_TEAMS
SPOOL policies/ptw_lv_teams_policies.sql
SET SERVEROUTPUT ON
BEGIN
    DBMS_OUTPUT.PUT_LINE(DBMS_METADATA.GET_DEPENDENT_DDL('RLS_POLICY', 'PTW_LV_TEAMS', 'PTW_PRO'));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
PROMPT Exporting RLS policies for PTW_LV_TEAM_TYPES
SPOOL policies/ptw_lv_team_types_policies.sql
SET SERVEROUTPUT ON
BEGIN
    DBMS_OUTPUT.PUT_LINE(DBMS_METADATA.GET_DEPENDENT_DDL('RLS_POLICY', 'PTW_LV_TEAM_TYPES', 'PTW_PRO'));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
PROMPT Exporting RLS policies for PTW_LV_USER_TYPES
SPOOL policies/ptw_lv_user_types_policies.sql
SET SERVEROUTPUT ON
BEGIN
    DBMS_OUTPUT.PUT_LINE(DBMS_METADATA.GET_DEPENDENT_DDL('RLS_POLICY', 'PTW_LV_USER_TYPES', 'PTW_PRO'));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
PROMPT Exporting RLS policies for PTW_LV_MONITORING_CONCERNS
SPOOL policies/ptw_lv_monitoring_concerns_policies.sql
SET SERVEROUTPUT ON
BEGIN
    DBMS_OUTPUT.PUT_LINE(DBMS_METADATA.GET_DEPENDENT_DDL('RLS_POLICY', 'PTW_LV_MONITORING_CONCERNS', 'PTW_PRO'));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
PROMPT Exporting RLS policies for PTW_LV_SITES
SPOOL policies/ptw_lv_sites_policies.sql
SET SERVEROUTPUT ON
BEGIN
    DBMS_OUTPUT.PUT_LINE(DBMS_METADATA.GET_DEPENDENT_DDL('RLS_POLICY', 'PTW_LV_SITES', 'PTW_PRO'));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
PROMPT Exporting RLS policies for PTW_CHECKLIST_RESPONSES
SPOOL policies/ptw_checklist_responses_policies.sql
SET SERVEROUTPUT ON
BEGIN
    DBMS_OUTPUT.PUT_LINE(DBMS_METADATA.GET_DEPENDENT_DDL('RLS_POLICY', 'PTW_CHECKLIST_RESPONSES', 'PTW_PRO'));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
PROMPT Exporting RLS policies for PTW_SIGNATURES
SPOOL policies/ptw_signatures_policies.sql
SET SERVEROUTPUT ON
BEGIN
    DBMS_OUTPUT.PUT_LINE(DBMS_METADATA.GET_DEPENDENT_DDL('RLS_POLICY', 'PTW_SIGNATURES', 'PTW_PRO'));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
PROMPT Exporting RLS policies for PTW_MONITORING_CHECKS
SPOOL policies/ptw_monitoring_checks_policies.sql
SET SERVEROUTPUT ON
BEGIN
    DBMS_OUTPUT.PUT_LINE(DBMS_METADATA.GET_DEPENDENT_DDL('RLS_POLICY', 'PTW_MONITORING_CHECKS', 'PTW_PRO'));
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-31603, -31608) THEN RAISE; END IF;
END;
/
SPOOL OFF
PROMPT DDL export complete.
