
  CREATE TABLE "PTW_PRO"."PTW_LV_TEAMS"
   (	"TEAM_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"COMPANY_ID" NUMBER NOT NULL ENABLE,
	"TEAM_NAME" VARCHAR2(200 BYTE) NOT NULL ENABLE,
	"IS_ACTIVE" VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
	"CREATED_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
	"CREATED_BY" VARCHAR2(100 BYTE),
	"MODIFIED_DATE" TIMESTAMP (6),
	"MODIFIED_BY" VARCHAR2(100 BYTE)
   ) ;
ALTER TABLE "PTW_PRO"."PTW_LV_TEAMS" ADD CONSTRAINT "CHK_PTW_LV_TEAMS_ACTIVE" CHECK (is_active IN ('Y','N')) ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_TEAMS" ADD CONSTRAINT "PK_PTW_LV_TEAMS" PRIMARY KEY ("TEAM_ID")
  USING INDEX  ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_TEAMS" ADD CONSTRAINT "UQ_PTW_LV_TEAMS" UNIQUE ("COMPANY_ID", "TEAM_NAME")
  USING INDEX  ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_TEAMS" ADD CONSTRAINT "FK_PTW_LV_TEAMS_COMPANY" FOREIGN KEY ("COMPANY_ID")
	  REFERENCES "PTW_PRO"."PTW_LV_COMPANIES" ("COMPANY_ID") ENABLE;
