
  CREATE TABLE "PTW_PRO"."PTW_LV_ROLES"
   (	"ROLE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"ROLE_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"ROLE_DESCRIPTION" VARCHAR2(500 BYTE),
	"IS_ADMIN_ROLE" VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
	"DISPLAY_ORDER" NUMBER DEFAULT 99 NOT NULL ENABLE,
	"IS_ACTIVE" VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE
   ) ;
ALTER TABLE "PTW_PRO"."PTW_LV_ROLES" ADD CONSTRAINT "CHK_PTW_LV_ROLES_ADMIN" CHECK (is_admin_role IN ('Y', 'N')) ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_ROLES" ADD CONSTRAINT "CHK_PTW_LV_ROLES_ACTIVE" CHECK (is_active IN ('Y', 'N')) ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_ROLES" ADD CONSTRAINT "PK_PTW_LV_ROLES" PRIMARY KEY ("ROLE_ID")
  USING INDEX  ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_ROLES" ADD CONSTRAINT "UQ_PTW_LV_ROLES_NAME" UNIQUE ("ROLE_NAME")
  USING INDEX  ENABLE;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "PTW_PRO"."PTW_LV_ROLES"  KUT$ ("ROLE_ID", "ROLE_NAME", "ROLE_DESCRIPTION", "IS_ADMIN_ROLE", "DISPLAY_ORDER", "IS_ACTIVE")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "ROLE_ID", "ROLE_NAME", "ROLE_DESCRIPTION", "IS_ADMIN_ROLE", "DISPLAY_ORDER", "IS_ACTIVE" FROM "PTW_PRO"."PTW_LV_ROLES"@ KU$;
