
  CREATE TABLE "PTW_PRO"."PTW_TYPES"
   (	"TYPE_ID" NUMBER DEFAULT "PTW_PRO"."PTW_TYPE_ID_SEQ"."NEXTVAL" NOT NULL ENABLE,
	"PTW_TYPE" VARCHAR2(30 BYTE),
	"TYPE_DESC" VARCHAR2(400 BYTE) NOT NULL ENABLE,
	"CREATED_DATE" DATE NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(30 BYTE),
	"AVAILABLE" VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE
   ) ;
ALTER TABLE "PTW_PRO"."PTW_TYPES" ADD CONSTRAINT "PTW_TYPES_PK" PRIMARY KEY ("TYPE_ID")
  USING INDEX  ENABLE;
