
  CREATE TABLE "PTW_PRO"."PTW_CHECKLIST_ITEMS"
   (	"CHECKLIST_ITEM_ID" NUMBER DEFAULT "PTW_PRO"."PTW_CHECKLIST_ITEM_SEQ"."NEXTVAL" NOT NULL ENABLE,
	"TYPE_ID" NUMBER NOT NULL ENABLE,
	"SECTION_CODE" VARCHAR2(30 BYTE) NOT NULL ENABLE,
	"ITEM_CODE" VARCHAR2(30 BYTE) NOT NULL ENABLE,
	"ITEM_SEQ" NUMBER NOT NULL ENABLE,
	"QUESTION_TEXT" VARCHAR2(500 BYTE) NOT NULL ENABLE,
	"HELP_TEXT" VARCHAR2(1000 BYTE),
	"RESPONSE_TYPE" VARCHAR2(20 BYTE) DEFAULT 'TRISTATE' NOT NULL ENABLE,
	"IS_ACTIVE" VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
	"CREATED_DATE" DATE NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(30 BYTE)
   ) ;
ALTER TABLE "PTW_PRO"."PTW_CHECKLIST_ITEMS" ADD CONSTRAINT "CHK_PTW_CI_SECTION" CHECK (section_code IN ('CONTROL_MEASURES','PPE')) ENABLE;
ALTER TABLE "PTW_PRO"."PTW_CHECKLIST_ITEMS" ADD CONSTRAINT "CHK_PTW_CI_RESP_TYPE" CHECK (response_type IN ('TRISTATE','TICK')) ENABLE;
ALTER TABLE "PTW_PRO"."PTW_CHECKLIST_ITEMS" ADD CONSTRAINT "CHK_PTW_CI_ACTIVE" CHECK (is_active IN ('Y','N')) ENABLE;
ALTER TABLE "PTW_PRO"."PTW_CHECKLIST_ITEMS" ADD CONSTRAINT "PK_PTW_CHECKLIST_ITEMS" PRIMARY KEY ("CHECKLIST_ITEM_ID")
  USING INDEX  ENABLE;
ALTER TABLE "PTW_PRO"."PTW_CHECKLIST_ITEMS" ADD CONSTRAINT "UQ_PTW_CHECKLIST_ITEMS" UNIQUE ("TYPE_ID", "ITEM_CODE")
  USING INDEX  ENABLE;
ALTER TABLE "PTW_PRO"."PTW_CHECKLIST_ITEMS" ADD CONSTRAINT "FK_PTW_CI_TYPE" FOREIGN KEY ("TYPE_ID")
	  REFERENCES "PTW_PRO"."PTW_TYPES" ("TYPE_ID") ENABLE;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "PTW_PRO"."PTW_CHECKLIST_ITEMS"  KUT$ ("CHECKLIST_ITEM_ID", "TYPE_ID", "SECTION_CODE", "ITEM_CODE", "ITEM_SEQ", "QUESTION_TEXT", "HELP_TEXT", "RESPONSE_TYPE", "IS_ACTIVE", "CREATED_DATE", "CREATED_BY")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "CHECKLIST_ITEM_ID", "TYPE_ID", "SECTION_CODE", "ITEM_CODE", "ITEM_SEQ", "QUESTION_TEXT", "HELP_TEXT", "RESPONSE_TYPE", "IS_ACTIVE", "CREATED_DATE", "CREATED_BY" FROM "PTW_PRO"."PTW_CHECKLIST_ITEMS"@ KU$;
