
  CREATE TABLE "PTW_PRO"."PTW_LV_SITES"
   (	"SITE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"COMPANY_ID" NUMBER NOT NULL ENABLE,
	"SITE_NAME" VARCHAR2(200 BYTE) NOT NULL ENABLE,
	"IS_ACTIVE" VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
	"CREATED_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
	"CREATED_BY" VARCHAR2(100 BYTE),
	"MODIFIED_DATE" TIMESTAMP (6),
	"MODIFIED_BY" VARCHAR2(100 BYTE)
   ) ;
ALTER TABLE "PTW_PRO"."PTW_LV_SITES" ADD CONSTRAINT "CHK_PTW_LV_SITES_ACTIVE" CHECK (is_active IN ('Y','N')) ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_SITES" ADD CONSTRAINT "PK_PTW_LV_SITES" PRIMARY KEY ("SITE_ID")
  USING INDEX  ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_SITES" ADD CONSTRAINT "UQ_PTW_LV_SITES" UNIQUE ("COMPANY_ID", "SITE_NAME")
  USING INDEX  ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_SITES" ADD CONSTRAINT "FK_PTW_LV_SITES_COMPANY" FOREIGN KEY ("COMPANY_ID")
	  REFERENCES "PTW_PRO"."PTW_LV_COMPANIES" ("COMPANY_ID") ENABLE;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "PTW_PRO"."PTW_LV_SITES"  KUT$ ("SITE_ID", "COMPANY_ID", "SITE_NAME", "IS_ACTIVE", "CREATED_DATE", "CREATED_BY", "MODIFIED_DATE", "MODIFIED_BY")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "SITE_ID", "COMPANY_ID", "SITE_NAME", "IS_ACTIVE", "CREATED_DATE", "CREATED_BY", "MODIFIED_DATE", "MODIFIED_BY" FROM "PTW_PRO"."PTW_LV_SITES"@ KU$;
