
  CREATE TABLE "PTW_PRO"."PTW_LV_USER_TYPES"
   (	"USER_TYPE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"COMPANY_ID" NUMBER NOT NULL ENABLE,
	"USER_ID" NUMBER NOT NULL ENABLE,
	"TYPE_ID" NUMBER NOT NULL ENABLE,
	"IS_ACTIVE" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"CREATED_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
	"CREATED_BY" VARCHAR2(100 BYTE),
	"MODIFIED_DATE" TIMESTAMP (6),
	"MODIFIED_BY" VARCHAR2(100 BYTE)
   ) ;
ALTER TABLE "PTW_PRO"."PTW_LV_USER_TYPES" ADD CONSTRAINT "CHK_PTW_LV_USER_TYPES_ACTIVE" CHECK (is_active IN ('Y','N')) ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_USER_TYPES" ADD CONSTRAINT "PK_PTW_LV_USER_TYPES" PRIMARY KEY ("USER_TYPE_ID")
  USING INDEX  ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_USER_TYPES" ADD CONSTRAINT "UQ_PTW_LV_USER_TYPES" UNIQUE ("USER_ID", "TYPE_ID")
  USING INDEX  ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_USER_TYPES" ADD CONSTRAINT "FK_PTW_LV_USER_TYPES_COMPANY" FOREIGN KEY ("COMPANY_ID")
	  REFERENCES "PTW_PRO"."PTW_LV_COMPANIES" ("COMPANY_ID") ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_USER_TYPES" ADD CONSTRAINT "FK_PTW_LV_USER_TYPES_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "PTW_PRO"."PTW_LV_USERS" ("USER_ID") ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_USER_TYPES" ADD CONSTRAINT "FK_PTW_LV_USER_TYPES_TYPE" FOREIGN KEY ("TYPE_ID")
	  REFERENCES "PTW_PRO"."PTW_TYPES" ("TYPE_ID") ENABLE;
