
  CREATE TABLE "PTW_PRO"."PTW_LV_USER_ROLE_ASSIGNMENTS"
   (	"USER_ROLE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"USER_ID" NUMBER NOT NULL ENABLE,
	"ROLE_ID" NUMBER NOT NULL ENABLE,
	"IS_ACTIVE" VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
	"GRANTED_BY" VARCHAR2(100 BYTE),
	"GRANTED_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
	"MODIFIED_DATE" TIMESTAMP (6),
	"MODIFIED_BY" VARCHAR2(100 BYTE)
   ) ;
ALTER TABLE "PTW_PRO"."PTW_LV_USER_ROLE_ASSIGNMENTS" ADD CONSTRAINT "CHK_PTW_UR_ACTIVE" CHECK (is_active IN ('Y', 'N')) ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_USER_ROLE_ASSIGNMENTS" ADD CONSTRAINT "PK_PTW_LV_USER_ROLES" PRIMARY KEY ("USER_ROLE_ID")
  USING INDEX  ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_USER_ROLE_ASSIGNMENTS" ADD CONSTRAINT "UQ_PTW_USER_ROLE" UNIQUE ("USER_ID", "ROLE_ID")
  USING INDEX  ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_USER_ROLE_ASSIGNMENTS" ADD CONSTRAINT "FK_PTW_UR_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "PTW_PRO"."PTW_LV_USERS" ("USER_ID") ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_USER_ROLE_ASSIGNMENTS" ADD CONSTRAINT "FK_PTW_UR_ROLE" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "PTW_PRO"."PTW_LV_ROLES" ("ROLE_ID") ENABLE;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "PTW_PRO"."PTW_LV_USER_ROLE_ASSIGNMENTS"  KUT$ ("USER_ROLE_ID", "USER_ID", "ROLE_ID", "IS_ACTIVE", "GRANTED_BY", "GRANTED_DATE", "MODIFIED_DATE", "MODIFIED_BY")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "USER_ROLE_ID", "USER_ID", "ROLE_ID", "IS_ACTIVE", "GRANTED_BY", "GRANTED_DATE", "MODIFIED_DATE", "MODIFIED_BY" FROM "PTW_PRO"."PTW_LV_USER_ROLE_ASSIGNMENTS"@ KU$;
