
  CREATE TABLE "PTW_PRO"."PTW_LV_EQUIPMENT_ISOLATION"
   (	"ISOLATION_ID" NUMBER DEFAULT "PTW_PRO"."PTW_LV_EQUIPMENT_ISOLATION_SEQ"."NEXTVAL",
	"PERMIT_ID" NUMBER NOT NULL ENABLE,
	"ROW_NUMBER" NUMBER(1,0) NOT NULL ENABLE,
	"EQUIPMENT_ISOLATED" VARCHAR2(200 BYTE),
	"MEANS_OF_ISOLATION" VARCHAR2(200 BYTE),
	"SAFETY_LOCK_NO" VARCHAR2(50 BYTE),
	"CREATED_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
	"MODIFIED_DATE" TIMESTAMP (6),
	"COMPANY_ID" NUMBER NOT NULL ENABLE
   ) ;
ALTER TABLE "PTW_PRO"."PTW_LV_EQUIPMENT_ISOLATION" ADD PRIMARY KEY ("ISOLATION_ID")
  USING INDEX  ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_EQUIPMENT_ISOLATION" ADD CONSTRAINT "FK_PTW_LV_ISO_PERMIT" FOREIGN KEY ("PERMIT_ID")
	  REFERENCES "PTW_PRO"."PTW_LV_PERMITS" ("PERMIT_ID") ON DELETE CASCADE ENABLE;
