
  CREATE TABLE "PTW_PRO"."PTW_LV_MONITORING_CONCERNS"
   (	"CONCERN_ID" NUMBER DEFAULT ptw_pro.ptw_lv_monitoring_concern_seq.NEXTVAL,
	"MONITORING_ID" NUMBER NOT NULL ENABLE,
	"CHECK_NUMBER" NUMBER(1,0) NOT NULL ENABLE,
	"CONCERN_DESCRIPTION" VARCHAR2(1000 BYTE),
	"ACTIONS_TAKEN" VARCHAR2(1000 BYTE),
	"HAPPY_TO_CONTINUE" VARCHAR2(1 BYTE),
	"CONCERN_PERSON_NAME" VARCHAR2(200 BYTE),
	"CONCERN_SIGNATURE" BLOB,
	"CONCERN_DATETIME" DATE,
	"CONCERN_LATITUDE" NUMBER,
	"CONCERN_LONGITUDE" NUMBER,
	"COMPANY_ID" NUMBER NOT NULL ENABLE,
	"CREATED_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
	"CREATED_BY" VARCHAR2(100 BYTE),
	"MODIFIED_DATE" TIMESTAMP (6),
	"MODIFIED_BY" VARCHAR2(100 BYTE)
   ) ;
ALTER TABLE "PTW_PRO"."PTW_LV_MONITORING_CONCERNS" ADD CONSTRAINT "CK_PTW_LV_MC_CHECK_NUMBER" CHECK (check_number IN (1,2,3)) ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_MONITORING_CONCERNS" ADD CONSTRAINT "CK_PTW_LV_MC_HAPPY" CHECK (happy_to_continue IN ('Y','N')) ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_MONITORING_CONCERNS" ADD PRIMARY KEY ("CONCERN_ID")
  USING INDEX  ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_MONITORING_CONCERNS" ADD CONSTRAINT "UQ_PTW_LV_MC_MONITORING_CHECK" UNIQUE ("MONITORING_ID", "CHECK_NUMBER")
  USING INDEX  ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_MONITORING_CONCERNS" ADD CONSTRAINT "FK_PTW_LV_MC_MONITORING" FOREIGN KEY ("MONITORING_ID")
	  REFERENCES "PTW_PRO"."PTW_LV_MONITORING" ("MONITORING_ID") ON DELETE CASCADE ENABLE;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "PTW_PRO"."PTW_LV_MONITORING_CONCERNS"  KUT$ ("CONCERN_ID", "MONITORING_ID", "CHECK_NUMBER", "CONCERN_DESCRIPTION", "ACTIONS_TAKEN", "HAPPY_TO_CONTINUE", "CONCERN_PERSON_NAME", "CONCERN_SIGNATURE", "CONCERN_DATETIME", "CONCERN_LATITUDE", "CONCERN_LONGITUDE", "COMPANY_ID", "CREATED_DATE", "CREATED_BY", "MODIFIED_DATE", "MODIFIED_BY")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "CONCERN_ID", "MONITORING_ID", "CHECK_NUMBER", "CONCERN_DESCRIPTION", "ACTIONS_TAKEN", "HAPPY_TO_CONTINUE", "CONCERN_PERSON_NAME", "CONCERN_SIGNATURE", "CONCERN_DATETIME", "CONCERN_LATITUDE", "CONCERN_LONGITUDE", "COMPANY_ID", "CREATED_DATE", "CREATED_BY", "MODIFIED_DATE", "MODIFIED_BY" FROM "PTW_PRO"."PTW_LV_MONITORING_CONCERNS"@ KU$;
