
  CREATE TABLE "PTW_PRO"."PTW_LV_CONTROL_MEASURES"
   (	"CONTROL_MEASURES_ID" NUMBER DEFAULT "PTW_PRO"."PTW_LV_CONTROL_MEASURES_SEQ"."NEXTVAL",
	"PERMIT_ID" NUMBER NOT NULL ENABLE,
	"CM_01_SITE_INDUCTION" VARCHAR2(2 BYTE),
	"CM_02_RISK_ASSESSMENT" VARCHAR2(2 BYTE),
	"CM_03_COMPETENCE_CHECKED" VARCHAR2(2 BYTE),
	"CM_04_HAZARDS_AWARE" VARCHAR2(2 BYTE),
	"CM_05_PPE_IDENTIFIED" VARCHAR2(2 BYTE),
	"CM_06_SOURCES_ISOLATED" VARCHAR2(2 BYTE),
	"CM_07_PROVED_DEAD" VARCHAR2(2 BYTE),
	"CM_08_STORED_ENERGY" VARCHAR2(2 BYTE),
	"CM_09_LIVE_COVERED" VARCHAR2(2 BYTE),
	"CM_10_NO_LIVE_WORK" VARCHAR2(2 BYTE),
	"CM_11_FIRST_AID" VARCHAR2(2 BYTE),
	"CM_12_BARRIERS" VARCHAR2(2 BYTE),
	"CM_13_ACCESS_EGRESS" VARCHAR2(2 BYTE),
	"CM_14_INSULATED_MATTING" VARCHAR2(2 BYTE),
	"CM_15_CALIBRATION_CURRENT" VARCHAR2(2 BYTE),
	"CM_16_DANGER_SIGNS" VARCHAR2(2 BYTE),
	"CREATED_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
	"MODIFIED_DATE" TIMESTAMP (6),
	"CM_LATITUDE" NUMBER,
	"CM_LONGITUDE" NUMBER,
	"COMPANY_ID" NUMBER NOT NULL ENABLE
   ) ;
ALTER TABLE "PTW_PRO"."PTW_LV_CONTROL_MEASURES" ADD PRIMARY KEY ("CONTROL_MEASURES_ID")
  USING INDEX  ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_CONTROL_MEASURES" ADD CONSTRAINT "FK_PTW_LV_CM_PERMIT" FOREIGN KEY ("PERMIT_ID")
	  REFERENCES "PTW_PRO"."PTW_LV_PERMITS" ("PERMIT_ID") ON DELETE CASCADE ENABLE;
