
  CREATE TABLE "PTW_PRO"."PTW_LV_USER_ROLES_OLD"
   (	"ROLE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"USERNAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ROLE_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"APP_ID" NUMBER,
	"IS_ACTIVE" VARCHAR2(1 BYTE) DEFAULT 'Y',
	"GRANTED_BY" VARCHAR2(100 BYTE),
	"GRANTED_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
	"MODIFIED_DATE" TIMESTAMP (6),
	"MOBILE_NO" VARCHAR2(30 BYTE),
	"EMAIL_ADDRESS" VARCHAR2(100 BYTE),
	"FIRST_NAME" VARCHAR2(100 BYTE),
	"LAST_NAME" VARCHAR2(100 BYTE),
	"COMPANY_NAME" VARCHAR2(200 BYTE)
   ) ;
ALTER TABLE "PTW_PRO"."PTW_LV_USER_ROLES_OLD" ADD CONSTRAINT "CHK_PTW_LV_ROLE_NAME" CHECK (
        role_name IN (
            'ADMIN',
            'ADMIN_CONTRACT_SUPPORT',
            'AUTHORISER',
            'ENGINEER',
            'READONLY'
        )
    ) DISABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_USER_ROLES_OLD" ADD PRIMARY KEY ("ROLE_ID")
  USING INDEX  ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_USER_ROLES_OLD" ADD CONSTRAINT "UQ_PTW_LV_USER_ROLE" UNIQUE ("USERNAME", "ROLE_NAME")
  USING INDEX  ENABLE;
