
  CREATE TABLE "PTW_PRO"."PTW_LV_USERS"
   (	"USER_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"USERNAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"FIRST_NAME" VARCHAR2(100 BYTE),
	"LAST_NAME" VARCHAR2(100 BYTE),
	"EMAIL_ADDRESS" VARCHAR2(200 BYTE),
	"MOBILE_NO" VARCHAR2(30 BYTE),
	"JOB_TITLE" VARCHAR2(100 BYTE),
	"IS_ACTIVE" VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
	"CREATED_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
	"CREATED_BY" VARCHAR2(100 BYTE),
	"MODIFIED_DATE" TIMESTAMP (6),
	"MODIFIED_BY" VARCHAR2(100 BYTE),
	"COMPANY_ID" NUMBER,
	"IS_SUPER_USER" VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
	"TEAM_ID" NUMBER
   ) ;
ALTER TABLE "PTW_PRO"."PTW_LV_USERS" ADD CONSTRAINT "CHK_PTW_LV_USERS_ACTIVE" CHECK (is_active IN ('Y', 'N')) ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_USERS" ADD CONSTRAINT "PK_PTW_LV_USERS" PRIMARY KEY ("USER_ID")
  USING INDEX  ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_USERS" ADD CONSTRAINT "UQ_PTW_LV_USERS_USERNAME" UNIQUE ("USERNAME")
  USING INDEX  ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_USERS" ADD CONSTRAINT "CHK_PTW_LV_USERS_SUPER" CHECK (is_super_user IN ('Y','N')) ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_USERS" ADD CONSTRAINT "FK_PTW_LV_USERS_COMPANY" FOREIGN KEY ("COMPANY_ID")
	  REFERENCES "PTW_PRO"."PTW_LV_COMPANIES" ("COMPANY_ID") ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_USERS" ADD CONSTRAINT "FK_PTW_LV_USERS_TEAM" FOREIGN KEY ("TEAM_ID")
	  REFERENCES "PTW_PRO"."PTW_LV_TEAMS" ("TEAM_ID") ENABLE;
