
  CREATE TABLE "PTW_PRO"."PTW_LV_MONITORING"
   (	"MONITORING_ID" NUMBER DEFAULT ptw_pro.ptw_lv_monitoring_seq.NEXTVAL,
	"PERMIT_ID" NUMBER NOT NULL ENABLE,
	"CHK_PERMIT_ON_DISPLAY" VARCHAR2(2 BYTE),
	"CHK_PERMIT_TIME" VARCHAR2(10 BYTE),
	"CHK_ACCESS_EGRESS" VARCHAR2(2 BYTE),
	"CHK_ACCESS_TIME" VARCHAR2(10 BYTE),
	"CHK_WARNING_SIGNS" VARCHAR2(2 BYTE),
	"CHK_WARNING_TIME" VARCHAR2(10 BYTE),
	"MS_CHECK1_DETAIL" VARCHAR2(1000 BYTE),
	"MS_CHECK1_TIME" VARCHAR2(10 BYTE),
	"MS_CHECK1_IN_ORDER" VARCHAR2(2 BYTE),
	"MS_CHECK1_COMMENTS" VARCHAR2(1000 BYTE),
	"MS_CHECK2_DETAIL" VARCHAR2(1000 BYTE),
	"MS_CHECK2_TIME" VARCHAR2(10 BYTE),
	"MS_CHECK2_IN_ORDER" VARCHAR2(2 BYTE),
	"MS_CHECK2_COMMENTS" VARCHAR2(1000 BYTE),
	"MS_CHECK3_DETAIL" VARCHAR2(1000 BYTE),
	"MS_CHECK3_TIME" VARCHAR2(10 BYTE),
	"MS_CHECK3_IN_ORDER" VARCHAR2(2 BYTE),
	"MS_CHECK3_COMMENTS" VARCHAR2(1000 BYTE),
	"MONITOR_NAME" VARCHAR2(200 BYTE),
	"MONITOR_SIGNATURE" BLOB,
	"MONITOR_DATE" DATE,
	"MONITOR_LATITUDE" NUMBER,
	"MONITOR_LONGITUDE" NUMBER,
	"CREATED_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
	"CREATED_BY" VARCHAR2(100 BYTE),
	"MODIFIED_DATE" TIMESTAMP (6),
	"MODIFIED_BY" VARCHAR2(100 BYTE),
	"PTW_TYPE" VARCHAR2(30 BYTE),
	"MONITORING_STATUS" VARCHAR2(20 BYTE),
	"COMPANY_ID" NUMBER NOT NULL ENABLE
   ) ;
ALTER TABLE "PTW_PRO"."PTW_LV_MONITORING" ADD PRIMARY KEY ("MONITORING_ID")
  USING INDEX  ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_MONITORING" ADD CONSTRAINT "FK_PTW_LV_MON_PERMIT" FOREIGN KEY ("PERMIT_ID")
	  REFERENCES "PTW_PRO"."PTW_LV_PERMITS" ("PERMIT_ID") ON DELETE CASCADE ENABLE;
