
  CREATE TABLE "PTW_PRO"."PTW_MONITORING_CHECKS"
   (	"MONITORING_CHECK_ID" NUMBER DEFAULT "PTW_PRO"."PTW_MONITORING_CHECK_SEQ"."NEXTVAL",
	"MONITORING_ID" NUMBER NOT NULL ENABLE,
	"CHECK_SEQ" NUMBER NOT NULL ENABLE,
	"DETAIL" VARCHAR2(1000 BYTE),
	"CHECK_TIME" VARCHAR2(10 BYTE),
	"IN_ORDER" VARCHAR2(2 BYTE),
	"COMMENTS" VARCHAR2(1000 BYTE),
	"COMPANY_ID" NUMBER NOT NULL ENABLE,
	"CREATED_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
	"CREATED_BY" VARCHAR2(100 BYTE),
	"MODIFIED_DATE" TIMESTAMP (6),
	"MODIFIED_BY" VARCHAR2(100 BYTE)
   ) ;
ALTER TABLE "PTW_PRO"."PTW_MONITORING_CHECKS" ADD CONSTRAINT "CHK_PTW_MC_IN_ORDER" CHECK (in_order IN ('Y','N')) ENABLE;
ALTER TABLE "PTW_PRO"."PTW_MONITORING_CHECKS" ADD CONSTRAINT "PK_PTW_MONITORING_CHECKS" PRIMARY KEY ("MONITORING_CHECK_ID")
  USING INDEX  ENABLE;
ALTER TABLE "PTW_PRO"."PTW_MONITORING_CHECKS" ADD CONSTRAINT "UQ_PTW_MONITORING_CHECKS" UNIQUE ("MONITORING_ID", "CHECK_SEQ")
  USING INDEX  ENABLE;
ALTER TABLE "PTW_PRO"."PTW_MONITORING_CHECKS" ADD CONSTRAINT "FK_PTW_MC_MONITORING" FOREIGN KEY ("MONITORING_ID")
	  REFERENCES "PTW_PRO"."PTW_LV_MONITORING" ("MONITORING_ID") ON DELETE CASCADE ENABLE;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "PTW_PRO"."PTW_MONITORING_CHECKS"  KUT$ ("MONITORING_CHECK_ID", "MONITORING_ID", "CHECK_SEQ", "DETAIL", "CHECK_TIME", "IN_ORDER", "COMMENTS", "COMPANY_ID", "CREATED_DATE", "CREATED_BY", "MODIFIED_DATE", "MODIFIED_BY")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "MONITORING_CHECK_ID", "MONITORING_ID", "CHECK_SEQ", "DETAIL", "CHECK_TIME", "IN_ORDER", "COMMENTS", "COMPANY_ID", "CREATED_DATE", "CREATED_BY", "MODIFIED_DATE", "MODIFIED_BY" FROM "PTW_PRO"."PTW_MONITORING_CHECKS"@ KU$;
