
  CREATE TABLE "PTW_PRO"."PTW_STAGE_LOCATIONS"
   (	"PERMIT_ID" NUMBER,
	"PERMIT_STAGE" VARCHAR2(100 BYTE),
	"LATITUDE" NUMBER,
	"LONGITUDE" NUMBER,
	"CREATED_DATE" DATE,
	"CREATED_BY" VARCHAR2(100 BYTE),
	"COMPANY_ID" NUMBER
   ) ;
ALTER TABLE "PTW_PRO"."PTW_STAGE_LOCATIONS" ADD CONSTRAINT "FK_PTW_STAGE_LOC_PERMIT" FOREIGN KEY ("PERMIT_ID")
	  REFERENCES "PTW_PRO"."PTW_LV_PERMITS" ("PERMIT_ID") ON DELETE CASCADE ENABLE;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "PTW_PRO"."PTW_STAGE_LOCATIONS"  KUT$ ("PERMIT_ID", "PERMIT_STAGE", "LATITUDE", "LONGITUDE", "CREATED_DATE", "CREATED_BY", "COMPANY_ID")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "PERMIT_ID", "PERMIT_STAGE", "LATITUDE", "LONGITUDE", "CREATED_DATE", "CREATED_BY", "COMPANY_ID" FROM "PTW_PRO"."PTW_STAGE_LOCATIONS"@ KU$;
