
  CREATE TABLE "PTW_PRO"."PTW_LV_COMPANIES"
   (	"COMPANY_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"COMPANY_NAME" VARCHAR2(200 BYTE) NOT NULL ENABLE,
	"COMPANY_CODE" VARCHAR2(30 BYTE),
	"IS_ACTIVE" VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
	"CREATED_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
	"CREATED_BY" VARCHAR2(100 BYTE),
	"MODIFIED_DATE" TIMESTAMP (6),
	"MODIFIED_BY" VARCHAR2(100 BYTE),
	"PERMIT_PREFIX" VARCHAR2(4 BYTE),
	"LAST_PERMIT_SEQ" NUMBER DEFAULT 0 NOT NULL ENABLE,
	"LAST_PERMIT_YEAR" VARCHAR2(4 BYTE),
	"HEADER_TEXT" VARCHAR2(255 BYTE)
   ) ;
ALTER TABLE "PTW_PRO"."PTW_LV_COMPANIES" ADD CONSTRAINT "CHK_PTW_LV_COMPANIES_ACTIVE" CHECK (is_active IN ('Y','N')) ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_COMPANIES" ADD CONSTRAINT "PK_PTW_LV_COMPANIES" PRIMARY KEY ("COMPANY_ID")
  USING INDEX  ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_COMPANIES" ADD CONSTRAINT "UQ_PTW_LV_COMPANIES_CODE" UNIQUE ("COMPANY_CODE")
  USING INDEX  ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_COMPANIES" ADD CONSTRAINT "CHK_PTW_COMPANIES_PREFIX" CHECK (
        permit_prefix IS NULL
        OR (
            LENGTH(TRIM(permit_prefix)) BETWEEN 1 AND 4
            AND UPPER(permit_prefix) = permit_prefix
        )
    ) ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_COMPANIES" ADD CONSTRAINT "UQ_PTW_COMPANIES_PREFIX" UNIQUE ("PERMIT_PREFIX")
  USING INDEX  ENABLE;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "PTW_PRO"."PTW_LV_COMPANIES"  KUT$ ("COMPANY_ID", "COMPANY_NAME", "COMPANY_CODE", "IS_ACTIVE", "CREATED_DATE", "CREATED_BY", "MODIFIED_DATE", "MODIFIED_BY", "PERMIT_PREFIX", "LAST_PERMIT_SEQ", "LAST_PERMIT_YEAR", "HEADER_TEXT")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "COMPANY_ID", "COMPANY_NAME", "COMPANY_CODE", "IS_ACTIVE", "CREATED_DATE", "CREATED_BY", "MODIFIED_DATE", "MODIFIED_BY", "PERMIT_PREFIX", "LAST_PERMIT_SEQ", "LAST_PERMIT_YEAR", "HEADER_TEXT" FROM "PTW_PRO"."PTW_LV_COMPANIES"@ KU$;
