
  CREATE TABLE "PTW_PRO"."PTW_TYPE_SECTIONS"
   (	"TYPE_ID" NUMBER NOT NULL ENABLE,
	"SECTION_CODE" VARCHAR2(30 BYTE) NOT NULL ENABLE
   ) ;
ALTER TABLE "PTW_PRO"."PTW_TYPE_SECTIONS" ADD CONSTRAINT "CK_PTW_TYPE_SECTIONS_CODE" CHECK (section_code IN ('EQUIPMENT_ISOLATION','MONITORING','CLIENT_PERMISSION')) ENABLE;
ALTER TABLE "PTW_PRO"."PTW_TYPE_SECTIONS" ADD CONSTRAINT "PK_PTW_TYPE_SECTIONS" PRIMARY KEY ("TYPE_ID", "SECTION_CODE")
  USING INDEX  ENABLE;
ALTER TABLE "PTW_PRO"."PTW_TYPE_SECTIONS" ADD FOREIGN KEY ("TYPE_ID")
	  REFERENCES "PTW_PRO"."PTW_TYPES" ("TYPE_ID") ENABLE;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "PTW_PRO"."PTW_TYPE_SECTIONS"  KUT$ ("TYPE_ID", "SECTION_CODE")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "TYPE_ID", "SECTION_CODE" FROM "PTW_PRO"."PTW_TYPE_SECTIONS"@ KU$;
