
  CREATE TABLE "PTW_PRO"."PTW_SIGNATURES"
   (	"SIGNATURE_ID" NUMBER DEFAULT "PTW_PRO"."PTW_SIGNATURE_SEQ"."NEXTVAL",
	"PERMIT_ID" NUMBER NOT NULL ENABLE,
	"STAGE" VARCHAR2(10 BYTE) NOT NULL ENABLE,
	"PERSON_NAME" VARCHAR2(200 BYTE),
	"SIGNATURE_BLOB" BLOB,
	"MOBILE_NO" VARCHAR2(50 BYTE),
	"COMPANY_NAME" VARCHAR2(200 BYTE),
	"EVENT_DATETIME" DATE,
	"LATITUDE" NUMBER,
	"LONGITUDE" NUMBER,
	"COMPANY_ID" NUMBER NOT NULL ENABLE,
	"CREATED_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
	"CREATED_BY" VARCHAR2(100 BYTE),
	"MODIFIED_DATE" TIMESTAMP (6),
	"MODIFIED_BY" VARCHAR2(100 BYTE),
	"AUTH_TO_DATETIME" DATE
   ) ;
ALTER TABLE "PTW_PRO"."PTW_SIGNATURES" ADD CONSTRAINT "PK_PTW_SIGNATURES" PRIMARY KEY ("SIGNATURE_ID")
  USING INDEX  ENABLE;
ALTER TABLE "PTW_PRO"."PTW_SIGNATURES" ADD CONSTRAINT "UQ_PTW_SIGNATURES" UNIQUE ("PERMIT_ID", "STAGE")
  USING INDEX  ENABLE;
ALTER TABLE "PTW_PRO"."PTW_SIGNATURES" ADD CONSTRAINT "CHK_PTW_SIG_STAGE" CHECK (stage IN ('AUTH','ACCEPT','CLEAR','CANCEL','CLOSE')) ENABLE;
ALTER TABLE "PTW_PRO"."PTW_SIGNATURES" ADD CONSTRAINT "FK_PTW_SIG_PERMIT" FOREIGN KEY ("PERMIT_ID")
	  REFERENCES "PTW_PRO"."PTW_LV_PERMITS" ("PERMIT_ID") ON DELETE CASCADE ENABLE;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "PTW_PRO"."PTW_SIGNATURES"  KUT$ ("SIGNATURE_ID", "PERMIT_ID", "STAGE", "PERSON_NAME", "SIGNATURE_BLOB", "MOBILE_NO", "COMPANY_NAME", "EVENT_DATETIME", "LATITUDE", "LONGITUDE", "COMPANY_ID", "CREATED_DATE", "CREATED_BY", "MODIFIED_DATE", "MODIFIED_BY", "AUTH_TO_DATETIME")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "SIGNATURE_ID", "PERMIT_ID", "STAGE", "PERSON_NAME", "SIGNATURE_BLOB", "MOBILE_NO", "COMPANY_NAME", "EVENT_DATETIME", "LATITUDE", "LONGITUDE", "COMPANY_ID", "CREATED_DATE", "CREATED_BY", "MODIFIED_DATE", "MODIFIED_BY", "AUTH_TO_DATETIME" FROM "PTW_PRO"."PTW_SIGNATURES"@ KU$;
