
  CREATE TABLE "PTW_PRO"."PTW_LV_PERMIT_PHOTOS"
   (	"PHOTO_ID" NUMBER DEFAULT ptw_pro.ptw_lv_photo_seq.NEXTVAL,
	"PERMIT_ID" NUMBER NOT NULL ENABLE,
	"PHOTO_DATA" BLOB NOT NULL ENABLE,
	"MIME_TYPE" VARCHAR2(100 BYTE) DEFAULT 'image/jpeg',
	"FILE_NAME" VARCHAR2(255 BYTE),
	"PHOTO_CAPTION" VARCHAR2(500 BYTE),
	"PHOTO_LATITUDE" NUMBER,
	"PHOTO_LONGITUDE" NUMBER,
	"UPLOADED_BY" VARCHAR2(100 BYTE),
	"UPLOADED_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
	"COMPANY_ID" NUMBER NOT NULL ENABLE
   ) ;
ALTER TABLE "PTW_PRO"."PTW_LV_PERMIT_PHOTOS" ADD CONSTRAINT "PK_PTW_LV_PERMIT_PHOTOS" PRIMARY KEY ("PHOTO_ID")
  USING INDEX  ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_PERMIT_PHOTOS" ADD CONSTRAINT "FK_PTW_LV_PHOTOS_PERMIT" FOREIGN KEY ("PERMIT_ID")
	  REFERENCES "PTW_PRO"."PTW_LV_PERMITS" ("PERMIT_ID") ON DELETE CASCADE ENABLE;
