
  CREATE TABLE "PTW_PRO"."PTW_STAGE_LOCATIONS"
   (	"PERMIT_ID" NUMBER,
	"PERMIT_STAGE" VARCHAR2(100 BYTE),
	"LATITUDE" NUMBER,
	"LONGITUDE" NUMBER,
	"CREATED_DATE" DATE,
	"CREATED_BY" VARCHAR2(100 BYTE),
	"COMPANY_ID" NUMBER
   ) ;
ALTER TABLE "PTW_PRO"."PTW_STAGE_LOCATIONS" ADD CONSTRAINT "FK_PTW_STAGE_LOC_PERMIT" FOREIGN KEY ("PERMIT_ID")
	  REFERENCES "PTW_PRO"."PTW_LV_PERMITS" ("PERMIT_ID") ON DELETE CASCADE ENABLE;
