
  CREATE TABLE "PTW_PRO"."PTW_LV_TEAM_TYPES"
   (	"TEAM_TYPE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"COMPANY_ID" NUMBER NOT NULL ENABLE,
	"TEAM_ID" NUMBER NOT NULL ENABLE,
	"TYPE_ID" NUMBER NOT NULL ENABLE,
	"IS_ACTIVE" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"CREATED_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
	"CREATED_BY" VARCHAR2(100 BYTE),
	"MODIFIED_DATE" TIMESTAMP (6),
	"MODIFIED_BY" VARCHAR2(100 BYTE)
   ) ;
ALTER TABLE "PTW_PRO"."PTW_LV_TEAM_TYPES" ADD CONSTRAINT "CHK_PTW_LV_TEAM_TYPES_ACTIVE" CHECK (is_active IN ('Y','N')) ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_TEAM_TYPES" ADD CONSTRAINT "PK_PTW_LV_TEAM_TYPES" PRIMARY KEY ("TEAM_TYPE_ID")
  USING INDEX  ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_TEAM_TYPES" ADD CONSTRAINT "UQ_PTW_LV_TEAM_TYPES" UNIQUE ("TEAM_ID", "TYPE_ID")
  USING INDEX  ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_TEAM_TYPES" ADD CONSTRAINT "FK_PTW_LV_TEAM_TYPES_COMPANY" FOREIGN KEY ("COMPANY_ID")
	  REFERENCES "PTW_PRO"."PTW_LV_COMPANIES" ("COMPANY_ID") ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_TEAM_TYPES" ADD CONSTRAINT "FK_PTW_LV_TEAM_TYPES_TEAM" FOREIGN KEY ("TEAM_ID")
	  REFERENCES "PTW_PRO"."PTW_LV_TEAMS" ("TEAM_ID") ENABLE;
ALTER TABLE "PTW_PRO"."PTW_LV_TEAM_TYPES" ADD CONSTRAINT "FK_PTW_LV_TEAM_TYPES_TYPE" FOREIGN KEY ("TYPE_ID")
	  REFERENCES "PTW_PRO"."PTW_TYPES" ("TYPE_ID") ENABLE;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "PTW_PRO"."PTW_LV_TEAM_TYPES"  KUT$ ("TEAM_TYPE_ID", "COMPANY_ID", "TEAM_ID", "TYPE_ID", "IS_ACTIVE", "CREATED_DATE", "CREATED_BY", "MODIFIED_DATE", "MODIFIED_BY")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "TEAM_TYPE_ID", "COMPANY_ID", "TEAM_ID", "TYPE_ID", "IS_ACTIVE", "CREATED_DATE", "CREATED_BY", "MODIFIED_DATE", "MODIFIED_BY" FROM "PTW_PRO"."PTW_LV_TEAM_TYPES"@ KU$;
