
  CREATE TABLE "PTW_PRO"."PTW_CHECKLIST_RESPONSES"
   (	"CHECKLIST_RESPONSE_ID" NUMBER DEFAULT "PTW_PRO"."PTW_CHECKLIST_RESPONSE_SEQ"."NEXTVAL",
	"PERMIT_ID" NUMBER NOT NULL ENABLE,
	"CHECKLIST_ITEM_ID" NUMBER NOT NULL ENABLE,
	"RESPONSE" VARCHAR2(2 BYTE),
	"COMPANY_ID" NUMBER NOT NULL ENABLE,
	"CREATED_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
	"CREATED_BY" VARCHAR2(100 BYTE),
	"MODIFIED_DATE" TIMESTAMP (6),
	"MODIFIED_BY" VARCHAR2(100 BYTE)
   ) ;
ALTER TABLE "PTW_PRO"."PTW_CHECKLIST_RESPONSES" ADD CONSTRAINT "CHK_PTW_CR_RESPONSE" CHECK (response IN ('Y','N','NA')) ENABLE;
ALTER TABLE "PTW_PRO"."PTW_CHECKLIST_RESPONSES" ADD CONSTRAINT "PK_PTW_CHECKLIST_RESPONSES" PRIMARY KEY ("CHECKLIST_RESPONSE_ID")
  USING INDEX  ENABLE;
ALTER TABLE "PTW_PRO"."PTW_CHECKLIST_RESPONSES" ADD CONSTRAINT "UQ_PTW_CHECKLIST_RESPONSES" UNIQUE ("PERMIT_ID", "CHECKLIST_ITEM_ID")
  USING INDEX  ENABLE;
ALTER TABLE "PTW_PRO"."PTW_CHECKLIST_RESPONSES" ADD CONSTRAINT "FK_PTW_CR_PERMIT" FOREIGN KEY ("PERMIT_ID")
	  REFERENCES "PTW_PRO"."PTW_LV_PERMITS" ("PERMIT_ID") ON DELETE CASCADE ENABLE;
ALTER TABLE "PTW_PRO"."PTW_CHECKLIST_RESPONSES" ADD CONSTRAINT "FK_PTW_CR_ITEM" FOREIGN KEY ("CHECKLIST_ITEM_ID")
	  REFERENCES "PTW_PRO"."PTW_CHECKLIST_ITEMS" ("CHECKLIST_ITEM_ID") ENABLE;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "PTW_PRO"."PTW_CHECKLIST_RESPONSES"  KUT$ ("CHECKLIST_RESPONSE_ID", "PERMIT_ID", "CHECKLIST_ITEM_ID", "RESPONSE", "COMPANY_ID", "CREATED_DATE", "CREATED_BY", "MODIFIED_DATE", "MODIFIED_BY")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "CHECKLIST_RESPONSE_ID", "PERMIT_ID", "CHECKLIST_ITEM_ID", "RESPONSE", "COMPANY_ID", "CREATED_DATE", "CREATED_BY", "MODIFIED_DATE", "MODIFIED_BY" FROM "PTW_PRO"."PTW_CHECKLIST_RESPONSES"@ KU$;
